version: "3.8"
services:
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    container_name: doraly-api
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - "5173:5173"
    container_name: doraly-frontend